### ISSUE TITLE
Feature request : Basic rails and minecart like features

### ISSUE THREAD

**Issue by Carbon-Ghost** [SvenKayser/JMOD#1]
Self explainatory, basically I want a unique set of rail with a unique minecart that can go on it ( which will be called "tram" ingame ) and if possible, make it move at a constant speed.
TLDR : Rails, set maxSpeed and acceleration as vars and Wagons that have isAffectedByGravity and speedConstant as vars ^^

**Comment by ghost** [comment]
While it's an intriguing idea to expand JMOD to this, I cannot make any estimations on when it will be doable.

**Comment by SvenKayser** [comment]
I'm still intrigued by the idea, but with other priorities at hand I'm not sure when and if I will implement this. If you are up to the task, please feel free to do it yourself once 1.0.5 is done, and submit a PR when done.

**Comment by SvenKayser** [comment]
I might pick this up eventually, but probably never. The offer to implement it yourself still stands.
