### ISSUE TITLE
Feature Request: Skyblock Support 

### ISSUE THREAD

**Issue by ghost** [SvenKayser/JMOD#12]
In order to allow Survival Industry to support Skyblock, we'll probably need to add the following features to JMOD:
1. The ability to add and remove recipes for the Ex Nihilo sieve.
2. The ability to add recipes for the RotaryCraft centrifuge, pulse jet furnace, compactor, and extractor (to preserve modpack permission, recipe removal should not be included).
3. Expand the tool repair feature to include Ex Nihilo tools, such as the crook and hammer.

Once these features are added, the "Ex Machina" jmod can be made for SI.

**Comment by SvenKayser** [comment]
1. Done in 1.0.4
2. Mostly done in 1.0.4
3. Scheduled for 1.0.6

Examples following.

**Comment by SvenKayser** [comment]
PulseJet and Compactor are done, Extractor.... I'll have to see if that's workable from inside JMOD, of if actually using the RoC config is the way to go here.

**Comment by ghost** [comment]
It should be doable; after all, the extractor [does have an API](https://github.com/ReikaKalseki/RotaryCraft/blob/master/API/ExtractAPI.java).  Besides, remember that [the extractor doesn't use items as inputs, it uses oredicts](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=26746).

In any event, we can should be able to oredict the ore gravel and ore sand as ore, then perhaps make a crafting recipe to convert the ore dust block into an ore dust item compatible with the extractor (which it can then use to make slurry).

**Comment by SvenKayser** [comment]
reference https://github.com/SvenKayser/JMOD-ExNihilo/commit/d9be38241542958d51fca71b5eca400e28f76bf0

**Comment by SvenKayser** [comment]
Sieve adding and remove done as of https://github.com/SvenKayser/JMOD-ExNihilo/commit/a78ec6ddc1390d2f8b2a0e734f3a05b52a5a26ab

**Comment by SvenKayser** [comment]
AddExtract done as of https://github.com/SvenKayser/JMOD-Rotarycraft/commit/b9e03d450ac676074b25080040cf032eec718415

All done.
