### ISSUE TITLE
[1.70.10] Can not change ToolMaterial 

### ISSUE THREAD

**Issue by nmarshall23** [SvenKayser/JMOD#2]
I'm testing JMOD as a replacement for squidutils. 

I find I can not change the ToolMaterial, for the Hammerz in the [hammerz mod](http://minecraft.curseforge.com/projects/hammerz)

Is there a way of seeing debugging info on why JMOD can't change those ToolMaterial?

**Comment by ghost** [comment]
I will have to dig into this mod to see how the tool materials are coded. If JMOD cannot change a tool Material it complains, so chances are that those Hammerz extend the Tool Class, but use a different mechanism than vanilla tools do.

Just to be clear: Are you trying to change a tools material's properties, and the new properties are not applied correctly, or try to assign a new tool material altogether?

**Comment by nmarshall23** [comment]
I am trying to change the tools material harvest level, along with the Durability .  

Changes to vanilla tools material are applied fine. It's just tools materials added by the Hammerz mod. To clarify, the Diamond Hammer has the harvest level and durability I have set in JMOD. However when I set Copper as defined in the Hammerz Mod, my changes are not set on those tools. 

Here is a link to the [Hammer Item source](https://github.com/VapourDrive/Hammerz/blob/1.7.10/src/main/java/vapourdrive/hammerz/items/Hammer.java).

I have a feeling this bug is caused by when in the Mod Init's order items are created. That because Hammerz Mod creates it's Hammers and tools material in the preInit() step, it's not possible, to change them.

**Comment by ghost** [comment]
JMOD patches Tool Material Values far later than that to accommodate for exactly such instances. I'll have to dig deeper into that.

**Comment by SvenKayser** [comment]
As of now I'm putting this rather far back on the list of priorities. If you have an idea how to solve this feel free to get it working yourself and give me PR when done.

**Comment by nmarshall23** [comment]
Good to see that your are back. I have fixed this in my branch, I too found it very confusing. I will prepare a merge for you.

**Comment by SvenKayser** [comment]
That's amazing. Thank you!

**Comment by SvenKayser** [comment]
Fixed as of https://github.com/SvenKayser/JMOD/pull/36/commits/e6d110a24817f2546a76a48d74bd45aba759bbb9 thanks to nmarshall23
