### ISSUE TITLE
Server is not sharing ore mining levels with client

### ISSUE THREAD

**Issue by ghost** [SvenKayser/JMOD#28]
When attempting to start a server game, the client does not properly report ore mining levels in WAILA.  This does not occur when the client is first used to launch a singleplayer game, or if the player first starts a singleplayer game, exits, and then launches the server without restarting the client.

It seems as though the changes made on the server doesn't actually get reported to the client; the client has to run a singleplayer game for the local jmod to tell it what changes are being made.

**Comment by SvenKayser** [comment]
On second thought this makes perfect sense.

The block altering event is actually "server started".... which of course doens't happen on the client unless there actually is a (single player mode) server started.

**Comment by SvenKayser** [comment]
Should be fixed as of https://github.com/SvenKayser/JMOD/commit/5fcff5dcc28bc1c23904633a6d3ce7af1a6af826

**Comment by ghost** [comment]
Checked and confirmed.
