### ISSUE TITLE
Crash when repairing enchanted iron armor in anvil

### ISSUE THREAD

**Issue by ghost** [SvenKayser/JMOD#29]
Apparently, the game crashes when the anvil is used to repair enchanted iron armor.  While this is happening with a server/client game, the crash is happening client-side.

[Crash Information](https://openeye.openmods.info/crashes/42b85887a5faee1a000cdb2b6ecb632d)

**Comment by SvenKayser** [comment]
Is that limited to iron armor items?

**Comment by ghost** [comment]
Well, it seems to be limited to armor, and the armor does not need to be enchanted.  It is not limited to iron; apparently the same thing happens with leather.  Tools seem to work without a problem.

**Comment by ghost** [comment]
Actually, it looks like the problem went away with enhancedAnvilRepair(false).  And the anvil still applies endurance repair through material pieces.  Maybe this might help?

**Comment by SvenKayser** [comment]
Fixed as of https://github.com/SvenKayser/JMOD/commit/df0008acd2549aee19aa2a4487896ce391063743
