### ISSUE TITLE
The alloying recipes for the RotaryCraft blast furnace are no longer working.

### ISSUE THREAD

**Issue by ghost** [SvenKayser/JMOD#32]
This evening, while attempting to make steel in the blast furnace, I discovered that all the alloying recipes disappeared.  The crafting recipes still work, as the example recipe (stone stairs using cobble) is still showing up correctly.

NOTE: The code being used is [here](https://github.com/reteo/JMOD-Collection/tree/master/ModAlter).

**Comment by SvenKayser** [comment]
Fixed as of https://github.com/SvenKayser/JMOD/commit/8e669f3af12ff339701b90298e575089fff79071
