### ISSUE TITLE
Ex Nihilo Tool Repair

### ISSUE THREAD

**Issue by ghost** [SvenKayser/JMOD#4]
The tools for Ex Nihilo ([ItemHammer*](https://bitbucket.org/Erasmus_Crowley/ex-nihilo/src/b0b582d711263ccb3f2048f9c8fdb9982a5340da/src/main/java/exnihilo/items/hammers/?at=master) and [ItemCrook](https://bitbucket.org/Erasmus_Crowley/ex-nihilo/src/b0b582d711263ccb3f2048f9c8fdb9982a5340da/src/main/java/exnihilo/items/ItemCrook.java?at=master&fileviewer=file-view-default)) don't break, but they also can't be repaired.

**Comment by SvenKayser** [comment]
Pulled up into 1.0.5

**Comment by SvenKayser** [comment]
Postponed back to 1.0.6

**Comment by SvenKayser** [comment]
Fixed as of https://github.com/SvenKayser/JMOD-ExNihilo/commit/d9be38241542958d51fca71b5eca400e28f76bf0
