### ISSUE TITLE
Wooden bucket is not interacting with the RotaryCraft fermenter

### ISSUE THREAD

**Issue by ghost** [SvenKayser/JMOD#40]
I'm not able to put water in a RotaryCraft fermenter using a wooden bucket.  Right-clicking the fermenter with the wooden bucket simply opens the GUI.  This was brought to my attention in reteo/Survival-Industry#107

**Comment by SvenKayser** [comment]
I will probably have to rework the buckets. The wooden buckets take a dirty shortcut and the fermenter is punishing me for that now.

**Comment by SvenKayser** [comment]
Wooden Buckets need a rewrite as of https://github.com/SvenKayser/JMOD/commit/59d4cb91f6e030657d86c55d55e700fddfaf0b9d anyways (since the old implementation just breaks with the module system thanks to hunger overhaul)

**Comment by SvenKayser** [comment]
Resolved as https://github.com/SvenKayser/JMOD/commit/ae4c14ec9d7a605149133e2c5c085dba911ce0e2 implements custom buckets that can interact with IFluidHandler TEs (such as the Fermenter)
