### ISSUE TITLE
Tool and Armor Repair Issues

### ISSUE THREAD

**Issue by ghost** [SvenKayser/JMOD#41]
Testing (reteo/Survival-Industry#111) demonstrates that:

* Tools will only accept one version of an oredicted material as a repair material.
* Armor made in JMOD will not accept any materials for repair.

**Comment by SvenKayser** [comment]
(Probably) fixed as of https://github.com/SvenKayser/JMOD/commit/012f9e2dfa3c986a8de34285b2ee8d8f306cb7cc
