### ISSUE TITLE
Add Function to Modify Food Values 

### ISSUE THREAD

**Issue by nmarshall23** [SvenKayser/JMOD#9]
Currently I use [hunger-overhaul](http://minecraft.curseforge.com/projects/hunger-overhaul), in my mod pack. That has a feature to customize food values in a json file. However, I would much rather use javascript to calculate food values. 

Would you be interested if I implemented this functionality and send you a Pull request?

**Comment by ghost** [comment]
I say go for it (not that I can actually accept them, but it never hurts to offer).  I believe the development branch is "indev," with the master being the release branch.

**Comment by ghost** [comment]
Out of curiosity, I was glancing at your code, and was wondering, why did you comment out the DecoCraft dye fix?

**Comment by nmarshall23** [comment]
When setting up my dev environment I couldn't find any code related to DecoCraft. I've been meaning to write up an empty stub for it, like I did for the DragonAPI stuff.

**Comment by ghost** [comment]
Ah, okay.  The reason for that code is that dyes created by JMOD do not work with Decocraft by default (which means, blue and green dyes are useless in the bench).  Like I said, I was just curious. :)

**Comment by SvenKayser** [comment]
Didn't find any Decocraft code either. I'm working on a crudely decompiled version.

**Comment by nmarshall23** [comment]
After forking jmod and playing with the codebase. I think this and other mod support should be added in child mods. Would make building JMOD simpler.

**Comment by SvenKayser** [comment]
I'll submit a request related to child mods in a issue tailored to this. As for the original issue regarding your pulling your code in, I'll close this for now since, afaik, the code works. Please re-open if need to work on this arises again.
